---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>My Custom Page</title>
    </head>
    <body>
        <h1>Welcome to My Custom NGINX Page!</h1>
        <p>This is custom HTML content served by NGINX.</p>
    </body>
    </html>
